### ISSUE TITLE
Cotton?

### ISSUE THREAD

**Issue by rugk** [rugk/crops-parser#9]
@westnordost Again (https://github.com/rugk/crops-parser/issues/2).

Recognizable as orchard?

![grafik](https://user-images.githubusercontent.com/11966684/27824995-784410ea-60ae-11e7-9141-fca9a53417bf.png)

**Comment by westnordost** [comment]
I would say no, it's farmland. As you said earlier, cotton plants are usually cultivated yearly.

**Comment by rugk** [comment]
No, I was wrong. You've corrected me there.

> Daher ist der Anbau von Zwischenfrüchten zur Verbesserung der Bodenqualität und zur Unterdrückung von Unkräutern kaum möglich. Besonders auf großen Flächen wird Baumwolle oft ohne Fruchtwechsel mit anderen Nutzpflanzen angebaut. Infolge dieser Monokulturen ist die großflächige Baumwollproduktion stark von Pflanzenschutzmitteln abhängig. Baumwolle gilt als das landwirtschaftliche Produkt mit dem höchsten Einsatz an Chemikalien. 

* [x] is perennial/always grown in monoculture
* [ ] is grown on orchards/satellite images can be confused with orchards (???)

Only the second thing is unclear to me.

**Comment by westnordost** [comment]
But it is planted newly every year and being harvested with tractors. So, okay, I guess it qualifies being tagged in OSM at all because it likely does not change but I'd still say that it should be tagged with landuse=farmland+crop=cotton then.
I think from satellite, it is likely that one does not mistake it for bushes but that one directly sees that it is a cotton plantation - at least when the plants are ripe.

**Comment by rugk** [comment]
Okay, but the thing is, we cannot include it in an orchard quest then. Either is is directly tagged farmland… or…?

Well… maybe if the plants are not ripe and it is incorrectly tagged as orchard. Could be similar to vineyards, they may also be recognized, but if not they may be tagged as orchards…

**Comment by westnordost** [comment]
Yes, so I'd exclude them.

**Comment by rugk** [comment]
Done in next commit.
